---
id: '8130423303258'
alias: Alarm - Triggered - Home
trigger:
  - platform: state
    entity_id: binary_sensor.basement_bathroom_sjcgq11lm_water_leak
    to: 'on'
  - platform: state
    entity_id: binary_sensor.laundry_room_lpg_sensor_gas
    to: 'on'
  - platform: state
    entity_id: binary_sensor.laundry_room_hs3sa_smoke
    to: 'on'
  - platform: state
    entity_id: binary_sensor.laundry_room_sjcgq11lm_water_leak
    to: 'on'
  - platform: state
    entity_id: binary_sensor.laundry_room_hs3sa_smoke
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_sjcgq11lm_water_leak
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_hs3sa_smoke
    to: 'on'
  - platform: state
    entity_id: binary_sensor.ground_floor_bathroom_sjcgq11lm_water_leak
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_home'
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
  - service: tts.google_say
    data:
      entity_id: media_player.studio_andrea_andrea_andrea_google_mini
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.laundry_room_lpg_sensor_gas" %}by the Gas sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.laundry_room_sjcgq11lm_water_leak" %}by the Leak sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.laundry_room_hs3sa_smoke" %}by the Smoke sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.basement_bathroom_sjcgq11lm_water_leak" %}by the Leak sensor in the Basemenet Bathroom
        {% elif trigger.entity_id == "binary_sensor.kitchen_sjcgq11lm_water_leak" %}by the Leak sensor in the Kitchen
        {% elif trigger.entity_id == "binary_sensor.kitchen_hs3sa_smoke" %}by the Smoke sensor in the Kitchen
        {% elif trigger.entity_id == "binary_sensor.ground_floor_bathroom_sjcgq11lm_water_leak" %}by the Leak sensor in the Ground Floor Bathroom
        {% else %}but the trigger cannot be identified
        {% endif %}
      language: 'en'
  - service: notify.alarm
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.laundry_room_lpg_sensor_gas" %}by the Gas sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.laundry_room_sjcgq11lm_water_leak" %}by the Leak sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.laundry_room_hs3sa_smoke" %}by the Smoke sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.basement_bathroom_sjcgq11lm_water_leak" %}by the Leak sensor in the Basemenet Bathroom
        {% elif trigger.entity_id == "binary_sensor.kitchen_sjcgq11lm_water_leak" %}by the Leak sensor in the Kitchen
        {% elif trigger.entity_id == "binary_sensor.ground_floor_bathroom_sjcgq11lm_water_leak" %}by the Leak sensor in the Ground Floor Bathroom
        {% else %}but the trigger cannot be identified
        {% endif %}
      data:
        color: "#FF3300"
        sticky: true
        persistent: false
        tag: alarm
        ttl: 0
        priority: high
  - service: notify.telegram_andrea
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.laundry_room_lpg_sensor_gas" %}by the Gas sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.laundry_room_sjcgq11lm_water_leak" %}by the Leak sensor in the Laundry Room
        {% elif trigger.entity_id == "binary_sensor.basement_bathroom_sjcgq11lm_water_leak" %}by the Leak sensor in the Basemenet Bathroom
        {% elif trigger.entity_id == "binary_sensor.kitchen_sjcgq11lm_water_leak" %}by the Leak sensor in the Kitchen
        {% elif trigger.entity_id == "binary_sensor.ground_floor_bathroom_sjcgq11lm_water_leak" %}by the Leak sensor in the Ground Floor Bathroom
        {% else %}but the trigger cannot be identified
        {% endif %}
#  - service: homeassistant.turn_on
#    data:
#      entity_id:
#        - light.patio_light
#        - light.studio_andrea_andrea_andrea_wall_light
#      rgb_color: [255,0,0]
#      brightness_pct: 100
#      transition: 1
#  - delay:
#      seconds: 30
#  - service: homeassistant.turn_off
#    data:
#      entity_id:
#        - light.patio_light
#        - light.studio_andrea_andrea_andrea_wall_light
