---
id: '8285888123905'
alias: Alarm - Triggered - Night
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_pir
    to: 'on'
  - platform: state
    entity_id: binary_sensor.ground_floor_bathroom_window_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_window_1_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_window_2_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_window_1_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_window_2_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_window_3_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_window_4_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.play_room_window_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.studio_andrea_window_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bathroom_mccgq01lm_contact
    to: 'on'
#  - platform: state
#    entity_id: binary_sensor.patio_pir
#    to: 'on'
  - platform: state
    entity_id: binary_sensor.patio_mccgq01lm_outside_contact
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_night'
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
#  - service: alarm_control_panel.alarm_trigger
#    entity_id: alarm_control_panel.home_alarm_mqtt
  - service: notify.alarm
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.living_room_pir" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.ground_floor_bathroom_window_contact" %}in the Ground Floor Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.kitchen_window_1_contact" %}in the Kitchen Window 1
        {% elif trigger.entity_id == "binary_sensor.kitchen_window_2_contact" %}in the Kitchen Window 2
        {% elif trigger.entity_id == "binary_sensor.living_room_window_1_contact" %}in the Living Room Window 1
        {% elif trigger.entity_id == "binary_sensor.living_room_window_2_contact" %}in the Living Room Window 2
        {% elif trigger.entity_id == "binary_sensor.living_room_window_3_contact" %}in the Living Room Window 3
        {% elif trigger.entity_id == "binary_sensor.living_room_window_4_contact" %}in the Living Room Window 4
        {% elif trigger.entity_id == "binary_sensor.play_room_window_contact" %}in the Play Room Window
        {% elif trigger.entity_id == "binary_sensor.studio_andrea_window_contact" %}in the Studio Andrea Window
        {% elif trigger.entity_id == "binary_sensor.master_bedroom_pir" %}in the Master Bedroom
        {% elif trigger.entity_id == "binary_sensor.studio_andrea_pir" %}in the Studio
        {% elif trigger.entity_id == "binary_sensor.bedroom_luca_pir" %}in Luca's Bedroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_contact" %}at the Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.patio_pir" %}in the Patio
        {% elif trigger.entity_id == "binary_sensor.patio_mccgq01lm_outside" %}at the Patio Door
        {% elif trigger.entity_id == "group.garage_room_pir" %}at the Garage Door
        {% else %}from Unknown Sensor
        {% endif %}
      data:
        color: "FF3300"
        sticky: true
        persistent: false
        tag: alarm
        ttl: 0
        priority: high
  - service: notify.telegram_andrea
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.living_room_pir" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.ground_floor_bathroom_window_contact" %}in the Ground Floor Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.kitchen_window_1_contact" %}in the Kitchen Window 1
        {% elif trigger.entity_id == "binary_sensor.kitchen_window_2_contact" %}in the Kitchen Window 2
        {% elif trigger.entity_id == "binary_sensor.living_room_window_1_contact" %}in the Living Room Window 1
        {% elif trigger.entity_id == "binary_sensor.living_room_window_2_contact" %}in the Living Room Window 2
        {% elif trigger.entity_id == "binary_sensor.living_room_window_3_contact" %}in the Living Room Window 3
        {% elif trigger.entity_id == "binary_sensor.living_room_window_4_contact" %}in the Living Room Window 4
        {% elif trigger.entity_id == "binary_sensor.play_room_window_contact" %}in the Play Room Window
        {% elif trigger.entity_id == "binary_sensor.studio_andrea_window_contact" %}in the Studio Andrea Window
        {% elif trigger.entity_id == "binary_sensor.master_bedroom_pi" %}in the Master Bedroom
        {% elif trigger.entity_id == "binary_sensor.studio_andrea_pir" %}in the Studio
        {% elif trigger.entity_id == "binary_sensor.bedroom_luca_pir" %}in Luca's Bedroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_contact" %}at the Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.patio_pir" %}in the Patio
        {% elif trigger.entity_id == "binary_sensor.patio_mccgq01lm_outside" %}at the Patio Door
        {% elif trigger.entity_id == "group.garage_room_pir" %}at the Garage Door
        {% else %}from Unknown Sensor
        {% endif %}
  - service: homeassistant.turn_on
    data:
      entity_id:
        - light.patio_light
        - light.studio_andrea_wall_light
      rgb_color: [255,0,0]
      brightness_pct: 100
      transition: 1
  - delay:
      seconds: 30
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.patio_light
        - light.studio_andrea_wall_light
