---
id: '8004104070932'
alias: Alarm - Triggered - Away
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_pir
    to: 'on'
  - platform: state
    entity_id: binary_sensor.studio_pir
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bedroom_luca_pir
    to: 'on'
  - platform: state
    entity_id: binary_sensor.master_bedroom_pir
    to: 'on'
  - platform: state
    entity_id: binary_sensor.garage_door
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bathroom_mccgq01lm_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.patio_pir
    to: 'on'
  - platform: state
    entity_id: binary_sensor.patio_MCCGQ01LM_outside
    to: 'on'
  - platform: state
    entity_id: binary_sensor.00000_cell_motion_detection
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_away'
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
#  - service: alarm_control_panel.alarm_trigger
#    entity_id: alarm_control_panel.home_alarm_mqtt
#  - service: mqtt.publish
#    data:
#      topic: zigbee2mqtt/house_alarm_siren/set
#      payload: '{"warning": {"duration": 2, "mode": "emergency", "strobe": true}}'
  - service: notify.alarm
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.living_room_pir" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.00000_cell_motion_detection" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.master_bedroom_pir" %}in the Master Bedroom
        {% elif trigger.entity_id == "binary_sensor.studio_pir" %}in the Studio
        {% elif trigger.entity_id == "binary_sensor.bedroom_luca_pir" %}in Luca's Bedroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_contact" %}at the Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.patio_pir" %}in the Patio
        {% elif trigger.entity_id == "binary_sensor.patio_MCCGQ01LM_outside" %}at the Patio Door
        {% elif trigger.entity_id == "binary_sensor.garage_room_pir" %}at the Garage Door
        {% else %}from Unknown Sensor
        {% endif %}
      data:
        color: "#FF3300"
        sticky: true
        persistent: false
        tag: alarm
        ttl: 0
        priority: high
  - service: notify.telegram_andrea
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.living_room_pir" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.00000_cell_motion_detection" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.master_bedroom_pir" %}in the Master Bedroom
        {% elif trigger.entity_id == "binary_sensor.studio_pir" %}in the Studio
        {% elif trigger.entity_id == "binary_sensor.bedroom_luca_pir" %}in Luca's Bedroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_contact" %}at the Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.patio_pir" %}in the Patio
        {% elif trigger.entity_id == "binary_sensor.patio_MCCGQ01LM_outside" %}at the Patio Door
        {% elif trigger.entity_id == "binary_sensor.garage_room_pir" %}at the Garage Door
        {% else %}from Unknown Sensor
        {% endif %}
  - service: camera.snapshot
    data:
      entity_id: camera.hallway
      filename: /home/ha/webcam/hallway.jpg
  - service: camera.snapshot
    data:
      entity_id: camera.living_room_camera_mediaprofile_channel1_mainstream
      filename: /home/ha/webcam/living_room.jpg
  - service: telegram_bot.send_photo
    data:
      target: !secret telegram_andrea_id
      caption: Hallway
      file: /home/ha/webcam/hallway.jpg
  - service: telegram_bot.send_photo
    data:
      target: !secret telegram_andrea_id
      caption: Living Room
      file: /home/ha/webcam/living_room.jpg
