---
id: '8130423303258'
alias: Alarm - Triggered - Home
initial_state: off
trigger:
#  - platform: state
#    entity_id: binary_sensor.studio_andrea_andrea_andrea_pir
#    to: 'on'
  - platform: state
    entity_id: binary_sensor.patio_mccgq01lm_outside_contact
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_home'
    - condition: state
      entity_id: binary_sensor.patio_pir
      state: 'off'
    - condition: state
      entity_id: light.patio_lights
      state: 'off'
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
#  - service: alarm_control_panel.alarm_trigger
#    entity_id: alarm_control_panel.home_alarm_mqtt
  - service: tts.google_say
    data:
      entity_id: media_player.studio_andrea_andrea_andrea_google_mini
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.living_room_pir" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.master_bedroom_pi" %}in the Master Bedroom
        {% elif trigger.entity_id == "binary_sensor.studio_andrea_andrea_andrea_pir" %}in the Studio
        {% elif trigger.entity_id == "binary_sensor.bedroom_luca_pir" %}in the Luca's Bedroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_contact" %}at the Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.patio_pir" %}in the Patio
        {% elif trigger.entity_id == "binary_sensor.patio_mccgq01lm_outside_contact" %}at the Patio Door
        {% elif trigger.entity_id == "group.garage_room_pir" %}at the Garage Door
        {% else %}from Unknown Sensor
        {% endif %}
      language: 'en'
  - service: notify.alarm
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.living_room_pir" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.master_bedroom_pi" %}in the Master Bedroom
        {% elif trigger.entity_id == "binary_sensor.studio_andrea_andrea_andrea_pir" %}in the Studio
        {% elif trigger.entity_id == "binary_sensor.bedroom_luca_pir" %}in the Luca's Bedroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_contact" %}at the Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.patio_pir" %}in the Patio
        {% elif trigger.entity_id == "binary_sensor.patio_mccgq01lm_outside_contact" %}at the Patio Door
        {% elif trigger.entity_id == "group.garage_room_pir" %}at the Garage Door
        {% else %}from Unknown Sensor
        {% endif %}
      data:
        color: "#FF3300"
        sticky: true
        persistent: false
        tag: alarm
        ttl: 0
        priority: high
  - service: notify.telegram_andrea
    data:
      title: "Home Alarm"
      message: >
        Alarm triggered
        {% if trigger.entity_id == "binary_sensor.living_room_pir" %}in the Living Room
        {% elif trigger.entity_id == "binary_sensor.master_bedroom_pi" %}in the Master Bedroom
        {% elif trigger.entity_id == "binary_sensor.studio_andrea_andrea_andrea_pir" %}in the Studio
        {% elif trigger.entity_id == "binary_sensor.bedroom_luca_pir" %}in the Luca's Bedroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_contact" %}at the Bathroom Window
        {% elif trigger.entity_id == "binary_sensor.patio_pir" %}in the Patio
        {% elif trigger.entity_id == "binary_sensor.patio_mccgq01lm_outside_contact" %}at the Patio Door
        {% elif trigger.entity_id == "group.garage_room_pir" %}at the Garage Door
        {% else %}from Unknown Sensor
        {% endif %}
  - service: homeassistant.turn_on
    data:
      entity_id:
        - light.patio_light
        - light.studio_andrea_andrea_andrea_wall_light
      rgb_color: [255,0,0]
      brightness_pct: 100
      transition: 1
  - delay:
      seconds: 30
  - service: homeassistant.turn_off
    data:
      entity_id:
        - light.patio_light
        - light.studio_andrea_andrea_andrea_wall_light
