---
id: '4970622506045'
alias: Alarm - Auto Arm - Home
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.holiday_mode
    to: 'off'
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
  - platform: time_pattern
    minutes: '*'
  - platform: state
    entity_id: group.family
    to: 'home'
  - platform: zone
    entity_id: device_tracker.citroen_cactus
    event: enter
    zone: zone.garage
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.home_alarm', 'armed_home') }}"
    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'home'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'on'
        - condition: state
          entity_id: person.andrea
          state: 'Garage'
        - condition: state
          entity_id: person.sonia
          state: 'Garage'
        - condition: state
          entity_id: person.luca_ianuncci_espejo
          state: 'Garage'
    - condition: or
      conditions:
        - condition: time
          after: '07:00:00'
          before: '01:00:00'
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.studio_andrea_computer_ping
              state: 'on'
            - condition: state
              entity_id: binary_sensor.living_room_tv
              state: 'on'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/house_alarm_siren/set
      payload: '{"warning": {"duration": 1, "mode": "stop", "strobe": false}}'
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret home_alarm_pin
#  - service: alarm_control_panel.alarm_arm_home
#    entity_id: alarm_control_panel.home_alarm_mqtt
#    data:
#      code: !secret home_alarm_pin
#  - service: tts.google_translate_say
#    data:
#      entity_id: media_player.studio_google_mini
#      message: "Switched to Home Mode" 
#      language: 'en'
#  - service: notify.alarm
#    data:
#      title: "Home Alarm Activated"
#      message: "Alarm automatically activated - Home mode"
