---
id: '2497388509899'
alias: Alarm - Auto Arm - Away
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.holiday_mode
    to: 'on'
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
  - platform: state
    entity_id: input_boolean.cleaning_mode
    to: 'off'
  - platform: time_pattern
    minutes: '*'
  - platform: state
    entity_id: group.family
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.home_alarm', 'armed_away') }}"
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: input_boolean.holiday_mode
              state: 'on'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'off'
            - condition: state
              entity_id: input_boolean.clenaing_mode
              state: 'off'
        - condition: and
          conditions:
            - condition: state
              entity_id: input_boolean.holiday_mode
              state: 'off'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'off'
            - condition: state
              entity_id: input_boolean.cleaning_mode
              state: 'off'
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - condition: not
      conditions:
        - condition: state
          entity_id: person.andrea
          state: 'Garage'
        - condition: state
          entity_id: person.sonia
          state: 'Garage'
        - condition: state
          entity_id: person.luca
          state: 'Garage'
action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret home_alarm_pin
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.house
#  - service: alarm_control_panel.alarm_arm_away
#    entity_id: alarm_control_panel.home_alarm_mqtt
#    data:
#      code: !secret home_alarm_pin
  - service: notify.alarm
    data:
      title: "Home Alarm Activated"
      message: "Alarm automatically activated - Away mode"
