---
id: '1679507404875'
alias: Alarm - Auto Arm - Night
initial_state: on
trigger:
  - platform: time
    at: '00:00:00'
  - platform: state
    entity_id: input_boolean.holiday_mode
    to: 'off'
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
  - platform: state
    entity_id: schedule.cleaning_mode
    to: 'off'
  - platform: state
    entity_id: group.family
    to: 'home'
  - platform: zone
    entity_id: device_tracker.citroen_cactus
    event: enter
    zone: zone.garage
  - platform: state
    entity_id: binary_sensor.studio_andrea_desk_computer_ping
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.living_room_tv
    to: 'off'
    for:
      minutes: 10
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.home_alarm', 'armed_night') }}"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: schedule.cleaning_mode
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'home'
        - condition: state
          entity_id: person.andrea
          state: 'Garage'
        - condition: state
          entity_id: person.sonia
          state: 'Garage'
        - condition: state
          entity_id: person.luca
          state: 'Garage'
    - condition: time
      after: '01:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: binary_sensor.studio_desk_computer_ping
      state: 'off'
    - condition: state
      entity_id: binary_sensor.living_room_tv
      state: 'off'
    - condition: and
      conditions:
        - condition: template
          value_template: '{% if states.binary_sensor.studio_andrea_desk_computer_ping is defined %} {{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.studio_andrea_desk_computer_ping.last_changed)) > 600 }} {% endif %}'
        - condition: template
          value_template: '{% if states.binary_sensor.living_room_tv is defined %} {{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.living_room_tv.last_changed)) > 600 }} {% endif %}'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/house_alarm_siren/set
      payload: '{"warning": {"duration": 0, "mode": "stop", "strobe": false}}'
  - service: alarm_control_panel.alarm_arm_night
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret home_alarm_pin
  - service: alarm_control_panel.alarm_arm_night
    entity_id: alarm_control_panel.house
#  - service: alarm_control_panel.alarm_arm_night
#    entity_id: alarm_control_panel.home_alarm_mqtt
#    data:
#      code: !secret home_alarm_pin
#  - service: notify.alarm
#    data:
#      title: "Home Alarm Activated"
#      message: "Alarm automatically activated - Night mode"
