---
id: '5263115271079'
alias: Alarm - Flood Alert
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.master_bathroom_sjcgq11lm_water_leak
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bathroom_mccgq01lm_water_leak
    to: 'on'
action:
#  - service: mqtt.publish
#    data:
#      topic: zigbee2mqtt/house_alarm_siren/set
#      payload: '{"warning": {"duration": 0, "mode": "stop", "strobe": true}}'
  - service: notify.alarm
    data:
      title: "Home Alarm"
      message: >
        Flood detected
        {% if trigger.entity_id == "binary_sensor.master_bathroom_sjcgq11lm_water_leak" %} in the Master Bathroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_water_leak" %} in the Bathroom
        {% elif trigger.entity_id == "binary_sensor.kitchen_sjcgq11lm_water_leak" %} in the Kitchen
        {% elif trigger.entity_id == "binary_sensor.patio_sjcgq11lm_water_leak" %} in the Patio
        {% elif trigger.entity_id == "binary_sensor.garage_sjcgq11lm_water_leak" %} in the Garage
        {% else %} from an Unknown Sensor
        {% endif %}
      data:
        color: "#FF3300"
        sticky: "true"
        tag: tag
        ttl: 0
        priority: high
  - service: tts.google_say
    data:
      entity_id: media_player.studio_andrea_google_mini
      message: >
        Flood detected
        {% if trigger.entity_id == "binary_sensor.master_bathroom_sjcgq11lm_water_leak" %} in the Master Bathroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_water_leak" %} in the Bathroom
        {% elif trigger.entity_id == "binary_sensor.kitchen_sjcgq11lm_water_leak" %} in the Kitchen
        {% elif trigger.entity_id == "binary_sensor.patio_sjcgq11lm_water_leak" %} in the Patio
        {% elif trigger.entity_id == "binary_sensor.garage_sjcgq11lm_water_leak" %} in the Garage
        {% else %} from an Unknown Sensor
        {% endif %}
      language: 'en'
  - service: notify.telegram_andrea
    data:
      title: "Home Alarm"
      message: >
        Flood detected
        {% if trigger.entity_id == "binary_sensor.master_bathroom_sjcgq11lm_water_leak" %} in the Master Bathroom
        {% elif trigger.entity_id == "binary_sensor.bathroom_mccgq01lm_water_leak" %} in the Bathroom
        {% elif trigger.entity_id == "binary_sensor.kitchen_sjcgq11lm_water_leak" %} in the Kitchen
        {% elif trigger.entity_id == "binary_sensor.patio_sjcgq11lm_water_leak" %} in the Patio
        {% elif trigger.entity_id == "binary_sensor.garage_sjcgq11lm_water_leak" %} in the Garage
        {% else %} from an Unknown Sensor
        {% endif %}
