---
# This is actually just a bootstrap for my Lovelace configuration.
# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control Panel
preload_cards:
  - card-tools
  - hui-element
  - markdown
preload_rows:
  - divider
#animated_background: !include lovelace/animated_backgrounds/default.yaml
decluttering_templates: !include_dir_merge_named lovelace/templates/
q_cards: !include_dir_merge_named lovelace/q-cards/
kiosk_mode:
  non_admin_settings:
    hide_sidebar: false
views:
  - !include lovelace/views/house.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/studio_andrea.yaml
  - !include lovelace/views/studio_sonia.yaml
  - !include lovelace/views/master_bedroom.yaml
  - !include lovelace/views/kids_bedroom.yaml
  - !include lovelace/views/guest_bedroom.yaml
  - !include lovelace/views/common_bathroom.yaml
  - !include lovelace/views/laundry_room.yaml
  - !include lovelace/views/patio.yaml
  - !include lovelace/views/garden.yaml
  - !include lovelace/views/surveillance.yaml
  - !include lovelace/views/plants.yaml
#  - !include lovelace/views/health.yaml
  - !include lovelace/views/weather.yaml
