---
id: '8042467782035'
alias: Studio Andrea - Amplifier Off
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: input_boolean.night_mode
    to: 'on'
  - platform: state
    entity_id: binary_sensor.studio_andrea_computer_ping
    to: 'off'
    for:
      seconds: 120
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: input_boolean.night_mode
              state: 'on'
            - condition: state
              entity_id: binary_sensor.studio_andrea_computer_ping
              state: 'on'
        - condition: state
          entity_id: binary_sensor.studio_andrea_computer_ping
          state: 'off'
    - condition: template
      value_template: "{{ states.media_player.spotify_andrea.state != 'playing' }}"
    - condition: template
      value_template: "{{ states.media_player.spotify_andrea.attributes.source != 'YAMAHA-RXV779' }}"
    - condition: template
      value_template: "{{ states.media_player.spotify_andrea.attributes.source != 'PC-SELLERONE' }}"
action:
  - service: media_player.turn_off
    entity_id: media_player.studio_andrea_amplifier
