---
id: '0249381851346'
alias: Studio Andrea - Andrea is back home
initial_state: off
trigger:
  - platform: homeassistant
    event: start
  - platform: zone
    entity_id: person.andrea
    zone: zone.home
    event: leave
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.studio_andrea_desk_computer_ping
      state: 'off'
      for:
        seconds: 60
    - condition: state
      entity_id: person.andrea
      state: 'not_home'
      for:
        hours: 12
action:
  - service: light.turn_off
    entity_id: light.studio_andrea_lights
  - service: shell_command.media01_off
  - service: shell_command.media02_off
  - service: shell_command.media03_off
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_1
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_2
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_usb_hub
  - service: media_player.turn_off
    entity_id: media_player.studio_andrea_amplifier
#  - service: switch.turn_off
#    entity_id: switch.studio_andrea_desk_computer_plug
  - service: switch.turn_off
    entity_id: switch.studio_andrea_usb_relay_01
