---
id: '5219767528180'
alias: Studio Andrea - Computer On - Home
initial_state: off
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.studio_andrea_desk_computer_ping
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.studio_andrea_desk_computer_ping
      state: 'on'
    - condition: state
      entity_id: person.andrea
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_uk
          state: 'off'
        - condition: time
          after: '18:30:00'
          before: '10:00:00'
action:
  - service: switch.turn_on
    entity_id: switch.studio_andrea_media03_wol
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_uk_powerstrip
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_lg_monitor_1
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_usb_hub
  - service: mqtt.publish
    data:
      topic: "wled/001/fx"
      payload: "74"
  - service: light.turn_off
    data:
      entity_id: light.studio_andrea_lights
      transition: 5
