---
id: '1686845537304'
alias: Studio Andrea - Computer On - Work
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.studio_andrea_computer_ping
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.studio_andrea_computer_ping
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: person.andrea
          state: 'home'
        - condition: state
          entity_id: person.andrea
          state: 'Garden'
    - condition: time
      after: '09:30:00'
      before: '18:30:00'
    - condition: state
      entity_id: binary_sensor.workday_uk
      state: 'on'
action:
  - service: switch.turn_on
    entity_id: switch.studio_andrea_media03_wol
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_uk_powerstrip
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_lg_monitor_1
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_lg_monitor_2
  - service: media_player.turn_on
    entity_id: media_player.studio_andrea_amplifier
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_usb_hub
#  - service: mqtt.publish
#    data:
#      topic: "wled/001/fx"
#      payload: "74"
  - service: light.turn_off
    data:
      entity_id: light.studio_andrea_lights
      transition: 10
