---
id: '2054121770849'
alias: Studio Andrea - Computer Off - Home
initial_state: off
trigger:
  - platform: state
    entity_id: binary_sensor.studio_andrea_computer_ping
    to: 'off'
    for:
      seconds: 120
condition:
  - condition: state
    entity_id: person.andrea
    state: 'home'
action:
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_usb_hub
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_2
