---
id: '1685034187571'
alias: Studio Andrea - Computer Off - Away
initial_state: off
trigger:
  - platform: state
    entity_id: binary_sensor.studio_andrea_computer_ping
    to: 'off'
    for:
      seconds: 120
condition:
  - condition: state
    entity_id: person.andrea
    state: 'not_home'
action:
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_computer_plug
  - service: media_player.turn_off
    entity_id: media_player.studio_andrea_amplifier
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_usb_hub
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_1
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_2
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_uk_powerstrip
