---
id: '5853092793985'
alias: Studio Andrea - Computer On - Away
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.studio_andrea_computer_ping
    to: 'on'
condition:
  - condition: state
    entity_id: person.andrea
    state: 'not_home'
action:
  - service: switch.turn_on
    entity_id: switch.studio_andrea_media03_wol
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_usb_hub
  - service: notify.andrea_oneplus_nord
    data:
      title: "Studio Andrea"
      message: "Computer has been turned on!"
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_1
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_2
