---
id: '9405955254911'
alias: Studio Andrea - Night
initial_state: off
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.studio_andrea_desk_computer_ping
    to: 'off'
  - platform: state
    entity_id: input_boolean.night_mode
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
    - condition: state
      entity_id: binary_sensor.studio_andrea_desk_computer_ping
      state: 'off'
      for:
        seconds: 60
action:
  - service: shell_command.media01_off
  - service: shell_command.media02_off
  - service: shell_command.media03_off
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_usb_hub
  - service: switch.turn_off
    entity_id: switch.studio_andrea_desk_lg_monitor_2
#  - service: switch.turn_off
#    entity_id: switch.studio_andrea_desk_computer_plug
#  - service: switch.turn_off
#    entity_id: switch.studio_andrea_desk_uk_powerstrip
#  - service: switch.turn_off
#    entity_id: switch.studio_andrea_desk_powerstrip_2
#  - service: switch.turn_off
#    entity_id: switch.studio_andrea_table_plug
