---
id: '4580432665563'
alias: Studio Andrea - Phone Charger On
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.andrea_oneplus_nord_battery_level
  - platform: state
    entity_id: sensor.andrea_oneplus_nord_battery_state
    to: 'discharging'
  - platform: state
    entity_id: input_number.oneplus_charger_lower_bound
  - platform: state
    entity_id: input_number.oneplus_charger_upper_bound
  - platform: zone
    entity_id: person.andrea
    zone: zone.home
    event: enter
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.studio_andrea_usb_relay_01
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: person.andrea
          state: 'home'
        - condition: state
          entity_id: person.andrea
          state: 'Garage'
    - condition: state
      entity_id: sensor.andrea_oneplus_nord_battery_state
      state: 'discharging'
    - condition: template
      value_template: '{{ (states.sensor.andrea_oneplus_nord_battery_level.state | int ) < ( states.input_number.oneplus_charger_upper_bound.state | int ) }}'
    - condition: not
      conditions:
        - condition: template
          value_template: '{{ ( states.sensor.andrea_oneplus_nord_battery_level.state | int ) > ( states.input_number.oneplus_charger_lower_bound.state | int ) }}'
action:
  - service: switch.turn_on
    entity_id: switch.studio_andrea_usb_relay_01
