---
id: '3347197456625'
alias: Studio Andrea - PIR Off
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.studio_andrea_pir
    to: 'off'
    for:
      seconds: '{{ states("input_number.lights_automations_duration_studio") | int }}'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.lights_automations_motion_studio
      state: 'on'
    - condition: state
      entity_id: light.studio_andrea_lights
      state: 'on'
action:
  - service: light.turn_off
    data:
      entity_id: light.studio_andrea_lights
      transition: 10
