---
id: '3857273939716'
alias: Studio Andrea - Spotify Idle to Off
initial_state: on
trigger:
  - platform: state
    entity_id: media_player.spotify_andrea
    to: "paused"
    for:
      minutes: 5
  - platform: state
    entity_id: media_player.spotify_andrea
    to: "idle"
    for:
      minutes: 5
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.studio_andrea_desk_computer_ping
      state: 'off'
    - condition: template
      value_template: "{{ is_state_attr('media_player.studio_andrea_amplifier', 'source', 'Spotify') }}"
action:
  - service: media_player.turn_off
    entity_id: media_player.studio_andrea_amplifier
