---
id: '5597305899393'
alias: Studio Andrea - Wall Light On
initial_state: on
trigger:
  - platform: state
    entity_id: light.studio_andrea_wall_lights
    from: 'unavailable'
    to: 'on'
action:
  - service: light.turn_on
    entity_id: light.studio_andrea_wall_lights
  - service: light.turn_off
    entity_id: light.studio_andrea_wall_lights
