---
id: '6157120614939'
alias: Studio Andrea - Workday
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: "09:30:00"
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.andrea
          state: 'home'
        - condition: state
          entity_id: person.andrea
          state: 'Garage'
    - condition: state
      entity_id: binary_sensor.workday_uk
      state: 'on'
    - condition: time
      after: '09:30:00'
      before: '12:00:00'
action:
  - service: switch.turn_on
    entity_id: switch.studio_andrea_table_plug
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_powerstrip_2
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_uk_powerstrip
#  - service: switch.turn_on
#    entity_id: switch.studio_andrea_media01_wol
  - service: switch.turn_on
    entity_id: switch.studio_andrea_media03_wol
  - delay:
      minutes: 5
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_computer_plug
  - delay:
      seconds: 5
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_computer_wol
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_lg_monitor_1
  - service: switch.turn_on
    entity_id: switch.studio_andrea_desk_lg_monitor_2
