save_current_target_temperature:
  description: Save the current target temperature for later restore.
  target:
    entity:
      domain: climate
      integration: better_thermostat
    device:
      integration: better_thermostat

restore_saved_target_temperature:
  description: Restore the saved target temperature.
  target:
    entity:
      domain: climate
      integration: better_thermostat
    device:
      integration: better_thermostat

set_temp_target_temperature:
  description: Set the target temperature to a temporay like night mode, and save the old one.
  fields:
    temperature:
      name: Target temperature
      description: The target temperature to set.
      example: 18.5
      required: true
      advanced: true
      selector:
        number:
          min: 0
          max: 35
          step: 0.5
          mode: box
  target:
    entity:
      domain: climate
      integration: better_thermostat
    device:
      integration: better_thermostat
