---
alias: "Telegram callback to stop alerts for garage door"
trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: "/garage_acknowledge"
action:
  - service: alert.turn_off
    target:
      entity_id: alert.garage_door