---
id: '6895632866996'
alias: Patio - Door Left Open for 10 Minutes
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.patio_mccgq01lm_outside_contact
    to: 'on'
    for:
      minutes: 15
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: 'disarmed'
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: 'armed_home'
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: 'armed_night'
action:
#  - service: light.turn_on
#    data:
#      entity_id: light.studio_wall_light
  - service: notify.alarm
    data:
      title: "Home Alarm"
      message: "Patio Door has been open for 15 minutes."
      data:
        color: "#FF3300"
        sticky: "true"
        tag: tag
        ttl: 0
  - service: tts.google_say
    data:
      entity_id: media_player.studio_google_mini
      message: "The patio door has been opened for 15 minutes."
      language: 'en'
