---
id: '8138002361695'
alias: Studio - Set Amplifier Volume for Spotify
initial_state: on
trigger:
  - platform: template
    value_template: "{{ is_state_attr('media_player.studio_amplifier', 'source', 'Spotify') }}"
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: media_player.spotify_andrea
      state: "paused"
    - condition: state
      entity_id: media_player.spotify_andrea
      state: "idle"
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.studio_amplifier
      volume_level: "0.7"
