---
id: '3398152523589'
alias: Studio - Set Amplifier Volume for PC
initial_state: on
trigger:
  - platform: template
    value_template: "{{ is_state_attr('media_player.studio_amplifier', 'source', 'PC') }}"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.studio_desk_andrea_computer_ping
      state: "on"
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.studio_amplifier
      volume_level: "0.9"
