---
id: '8857948807317'
alias: Studio - PIR On
initial_state: on
trigger:
  - platform: state
    entity_id: group.studio_pir
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.lights_automations_motion_house
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_automations_motion_studio
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.night_mode
          state: 'on'
        - condition: template
          value_template: >-
            {% if is_state("input_boolean.lights_automations_lux_studio", "on") %}
              {% if (states("sensor.patio_gzcgq01lm_illuminance_lux") | int) <= (states("input_number.lights_automations_lux_studio") | int) %}
                true
              {% else %}
                false
              {% endif %}
            {% else %}
              true
            {% endif %}
#    - condition: state
#      entity_id: light.studio_lights
#      state: 'off'
    - condition: state
      entity_id: binary_sensor.studio_desk_andrea_computer_ping
      state: 'off'
    - condition: state
      entity_id: binary_sensor.studio_desk_sonia_laptop_ping
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.studio_desk_sonia_laptop_work_ping
          state: 'off'
        - condition: not
          conditions:
            - condition: time
              after: '07:00:00'
              before: '19:30:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: 'disarmed'
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: 'armed_home'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.studio_lights
      transition: 10
#  - service: scene.turn_on
#    data:
#      entity_id: scene.studio_night
#      transition: 5
