---
id: '5212779435330'
alias: Master Bathroom - Humidity Alert
initial_state: on
trigger:
  - platform: numeric_state
    entity_id: sensor.master_bathroom_huimidity
    above: '80'
    for:
      minutes: 5
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: binary_sensor.master_bathroom_window
      state: 'off'
action:
  - service: tts.google_say
    data:
      entity_id: media_player.studio_andrea_google_mini
      message: "The humidity in the master bathroom is too high, please open the window"
      language: "en"
  - service: notify.telegram_andrea
    data:
      title: "Master Bathroom"
      message: "The humidity in the master bathroom is too high, please open the window"
