---
id: '795773894926300'
# Alert for when the Washing Machine Pods are running out
alias: Laundry Room - Washing Machine - Pods
initial_state: on
trigger:
  - platform: numeric_state
    entity_id: counter.laundry_room_washing_machine_pods
    below: 15
action:
  - service: notify.telegram_andrea
    data:
      title: "Laundry Room"
      message: "Washing Machine pods are running out ({{ states('counter.washing_machine_pods')}} left). Please remember to buy them!"
