---
id: '5708782140671'
# When power is detected, and the washing machine is not in 
# the Running state, change the status of the washing machine
# to Running. 
# The status check will ensure we don't try to put the state 
# to Running each time the power level changes, and we're already
# in the Running state.
alias: Laundry Room - Washing Machine - Starting
initial_state: on
trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_room_washing_machine_plug_energy_power
    above: 1
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.laundry_room_washing_machine_status
      state: 'Idle'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.laundry_room_washing_machine_status
      option: 'Starting'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.laundry_room_washing_machine_current_energy
      value: "{{ states('sensor.laundry_room_washing_machine_plug_energy_today') }}"
