---
id: '1084971662961'
# When power is detected, and the washing machine is not in 
# the Running state, change the status of the washing machine
# to Running. 
# The status check will ensure we don't try to put the state 
# to Running each time the power level changes, and we're already
# in the Running state.
alias: Laundry Room - Washing Machine - Done
initial_state: on
trigger:
  - platform: numeric_state
    entity_id: sensor.laundry_room_washing_machine_plug_energy_power
    below: 5
    for:
      seconds: 15
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.laundry_room_washing_machine_status
      state: 'Spinning'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.laundry_room_washing_machine_status
      option: 'Done'
  - service: tts.google_say
    data:
      entity_id: media_player.studio_google_mini
      message: "Washing Machine is now done. Energy consumed was {{ states('sensor.laundry_room_washing_machine_plug_energy_today')|float - states('input_number.laundry_room_washing_machine_current_energy')|float | round(2) }}kWh"
      language: "en"
  - service: notify.telegram_andrea
    data:
      title: "Laundry Room"
      message: "Washing Machine is now done. Energy consumed: {{ states('sensor.laundry_room_washing_machine_plug_energy_today')|float - states('input_number.laundry_room_washing_machine_current_energy')|float | round(3) }}kWh"
  - service: tts.google_say
    data:
      entity_id: media_player.living_room_google_tv
      message: "Washing Machine is now done"
      language: "en"
  - service: input_number.set_value
    data_template:
      entity_id: input_number.laundry_room_washing_machine_current_energy
      value: "0"
