---
id: '5176015904441'
alias: System - Start Backup to NAS MEDIA01
initial_state: on
trigger:
  - platform: time
    at: '02:15:00'
condition:
  condition: and
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.samba_backup
          state: 'RUNNING'
action:
  - service: switch.turn_on
    entity_id: switch.studio_andrea_andrea_media01_wol
  - delay: '00:05:00'
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: trigger
  - delay: '00:30:00'
  - service: switch.turn_off
    entity_id: switch.studio_andrea_andrea_media01_wol
