---
id: '1541959637947'
alias: System - Refresh date countdown sensors
initial_state: on
trigger:
  - platform: time
    at: '00:00:01'
  - platform: homeassistant
    event: start
action:
  - service: python_script.date_countdown
    data:
      name: Andrea
      type: birthday
      date: !secret andrea_birthday
  - service: python_script.date_countdown
    data:
      name: Sonia
      type: birthday
      date: !secret sonia_birthday
  - service: python_script.date_countdown
    data:
      name: Luca
      type: birthday
      date: !secret luca_birthday
  - service: python_script.date_countdown
    data:
      name: Maurizio
      type: birthday
      date: !secret maurizio_birthday
  - service: python_script.date_countdown
    data:
      name: Patrizia
      type: birthday
      date: !secret patrizia_birthday
  - service: python_script.date_countdown
    data:
      name: Alessandra
      type: birthday
      date: !secret alessandra_birthday
  - service: python_script.date_countdown
    data:
      name: Martina
      type: birthday
      date: !secret martina_birthday
  - service: python_script.date_countdown
    data:
      name: "Andrea Sonia"
      type: anniversary
      date: !secret andrea_sonia_anniversary
