---
id: '6020975345972'
#
# Sync devices to Google Assistant
#
alias: System - Google Assistant Device Syncs
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '00:00:00'
action:
  - service: google_assistant.request_sync
#    data:
#      agent_user_id: !secret andrea_user_id
