---
id: '8925657190164'
alias: Mobile - Push Notification - Studio Light On
trigger:
  platform: event
  event_type: mobile_app_notification_action
  event_data:
    action: studio_andrea_andrea_wall_light_on
action:
  - service: light.turn_on
    data:
      entity_id: light.studio_andrea_andrea_wall_light
      brightness_pct: 10
