---
id: '548588280111608'
alias: "Lights - Adaptive lighting - Enable Sleep Mode"
trigger:
  - platform: state
    entity_id: input_boolean.night_mode
  - platform: homeassistant
    event: start
variables:
  night_mode: "{{ states('input_boolean.night_mode') }}"
action:
  service: "switch.turn_{{ night_mode }}"
  entity_id:
#    - switch.adaptive_lighting_sleep_mode_front_garden
#    - switch.adaptive_lighting_sleep_mode_back_garden
#    - switch.adaptive_lighting_sleep_mode_front_patio
#    - switch.adaptive_lighting_sleep_mode_back_patio
#    - switch.adaptive_lighting_sleep_mode_ground_floor_entrance
    - switch.adaptive_lighting_sleep_mode_ground_floor_corridor
    - switch.adaptive_lighting_sleep_mode_first_floor_corridor
    - switch.adaptive_lighting_sleep_mode_first_floor_stairs
    - switch.adaptive_lighting_sleep_mode_living_room
#    - switch.adaptive_lighting_sleep_mode_kitchen
    - switch.adaptive_lighting_sleep_mode_play_room
    - switch.adaptive_lighting_sleep_mode_studio_andrea
    - switch.adaptive_lighting_sleep_mode_studio_sonia
    - switch.adaptive_lighting_sleep_mode_kids_bedroom
    - switch.adaptive_lighting_sleep_mode_common_bathroom
    - switch.adaptive_lighting_sleep_mode_master_bedroom
    - switch.adaptive_lighting_sleep_mode_master_bathroom
    - switch.adaptive_lighting_sleep_mode_guest_bedroom
#    - switch.adaptive_lighting_sleep_mode_garage
#    - switch.adaptive_lighting_sleep_mode_laundry_room

