---
id: '8961302510647'
alias: Studio - Andrea - Amplifier On
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.night_mode
    to: 'off'
  - platform: state
    entity_id: media_player.studio_amplifier
    to: "on"
  - platform: state
    entity_id: media_player.studio_amplifier
    to: "idle"
  - platform: state
    entity_id: binary_sensor.studio_desk_andrea_computer_ping
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: binary_sensor.studio_desk_andrea_computer_ping
      state: 'on'
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('media_player.studio_amplifier', 'source', 'Spotify') }}"
            - condition: or
              conditions:
                - condition: state
                  entity_id: media_player.spotify_andrea
                  state: "paused"
                - condition: state
                  entity_id: media_player.spotify_andrea
                  state: "idle"
        - condition: or
          conditions:
            - condition: state
              entity_id: media_player.studio_amplifier
              state: 'off'
            - condition: state
              entity_id: media_player.studio_amplifier
              state: 'idle'
action:
  - service: media_player.turn_on
    entity_id: media_player.studio_amplifier
  - delay:
      seconds: 5
  - service: media_player.select_source
    data:
      entity_id: media_player.studio_amplifier
      source: PC
