---
id: '0594999905433'
alias: Studio - Andrea is back home
initial_state: on
trigger:
  - platform: zone
    entity_id: person.andrea
    zone: zone.home
    event: enter
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.studio_andrea_computer_plug
      state: 'off'
action:
  - service: switch.turn_on
    entity_id: switch.studio_media03_wol
  - delay:
      seconds: 120
  - service: switch.turn_on
    entity_id: switch.studio_andrea_lg_monitor_1
  - service: switch.turn_on
    entity_id: switch.studio_andrea_computer_plug
