---
id: '6498492866276'
# When power is detected, and the dish washer is not in 
# the Running state, change the status of the.kitchen_dishwasher
# to Running. 
# The status check will ensure we don't try to put the state 
# to Running each time the power level changes, and we're already
# in the Running state.
alias: Kitchen - Dishwasher - Done
initial_state: on
trigger:
  - platform: numeric_state
    entity_id: sensor.kitchen_dishwasher_plug_energy_power
    below: 2
    for:
      seconds: 15
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.kitchen_dishwasher_status
      state: 'Drying'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.kitchen_dishwasher_status
      option: 'Done'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.kitchen_dishwasher_current_energy
      value: "0"
  - service: tts.google_say
    data:
      entity_id: media_player.studio_andrea_google_mini
      message: "Dishwasher is now done"
#      message: "Dishwasher is now done. Energy consumed was {{ states('sensor.kitchen_dishwasher_plug_energy_today')|float - states('input_number.kitchen_dishwasher_current_energy')|float | round(2) }}kWh"
      language: "en"
  - service: notify.telegram_andrea
    data:
      title: "Kitchen"
      message: "Dishwasher is now done. Energy consumed: {{ states('sensor.kitchen_dishwasher_plug_energy_today')|float - states('input_number.kitchen_dishwasher_current_energy')|float | round(3) }}kWh"
  - service: notify.living_room_chromecast
    data:
      title: "Kitchen"
      message: "Dishwasher is now done"
      fontsize: "large"
      position: "center"
      duration: 2
      transparency: "20%"
      color: "blue"
      interrupt: 1
