---
id: '7526170396705'
alias: House - Andrea is home
initial_state: on
trigger:
  - platform: zone
    entity_id: person.andrea
    zone: zone.home
    event: enter
condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ not is_state('person.sonia', 'home') }}"
    - condition: time
      after: '09:00:00'
      before: '23:00:00'
action:
  - service: tts.google_say
    data:
      entity_id: media_player.studio_andrea_google_mini
      message: 'Welcome home master'
      language: 'en'
