---
id: '8126035620144'
alias: House - Cleaning Mode Deactivated
initial_state: on
trigger:
  - platform: time
    at: "14:30:00"
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - fri
    - condition: state
      entity_id: input_boolean.cleaning_mode
      state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.cleaning_mode
  - service: notify.mobile_app_andrea_oneplus_nord
    data:
      title: "Home"
      message: "Cleaning Mode Deactivated"
      data:
        color: "#33CC33"
        sticky: "false"
        tag: tag
  - service: tts.google_say
    data:
      entity_id: media_player.studio_andrea_google_mini
      message: "Cleaning Mode Deactivated"
      language: 'en'
