---
id: '3641894765835'
alias: House - Guest Mode Activated
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: time
      after: '09:00:00'
      before: '23:00:00'
action:
  - service: notify.mobile_app_andrea_oneplus_nord
    data:
      title: "Home Alarm"
      message: "Guest Mode Activated. Alarm Disarmed"
      data:
        color: "#0066FF"
        sticky: "false"
        tag: tag
  - service: tts.google_say
    data:
      entity_id: media_player.studio_google_mini
      message: "Guest Mode Activated"
      language: 'en'
