---
alias: Alarm - Guest Mode Deactivated
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
condition:
  condition: and
  conditions:
    - condition: time
      after: '09:00:00'
      before: '23:00:00'
action:
  - service: notify.mobile_app_andrea_oneplus_5
    data:
      title: "Home Alarm"
      message: "Guest Mode Deactivated. Alarm Armed"
      data:
        color: "#33CC33"
        sticky: "false"
        tag: tag
  - service: tts.google_translate_say
    data:
      entity_id: media_player.studio_google_mini
      message: "Guest Mode Deactivated"
      language: 'en'
