---
id: '2152045805703'
alias: House - Mold Alert
initial_state: on
trigger:
#  - platform: numeric_state
#    entity_id: sensor.house_mold_indicator
#    above: 85
#    for:
#      minutes: 5
  - platform: numeric_state
    entity_id: sensor.living_room_mold_indicator
    above: 85
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.kitchen_mold_indicator
    above: 85
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.bedroom_luca_mold_indicator
    above: 85
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.bathroom_mold_indicator
    above: 85
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.master_bedroom_mold_indicator
    above: 85
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.master_bathroom_mold_indicator
    above: 85
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.studio_andrea_mold_indicator
    above: 85
    for:
      minutes: 5
action:
  - service: notify.alarm
    data:
      title: 'Mold Alert'
      message: >
        Mold alert
        {% if trigger.entity_id == "sensor.living_room_mold_indicator" %}in the Living Room ({{ states.sensor.living_room_mold_indicator.state }}%)
        {% elif trigger.entity_id == "sensor.kitchen_mold_indicator" %}in the Kitchen Room ({{ states.sensor.kitchen_mold_indicator.state }}%)
        {% elif trigger.entity_id == "sensor.bedroom_luca_mold_indicator" %}in the Luca's Bedroom ({{ states.sensor.bedroom_luca_mold_indicator.state }}%)
        {% elif trigger.entity_id == "sensor.bathroom_mold_indicator" %}in the Bathroom ({{ states.sensor.bathroom_mold_indicator.state }}%)
        {% elif trigger.entity_id == "sensor.master_bedroom_mold_indicator" %}in the Master Bedroom ({{ states.sensor.master_bedroom_mold_indicator.state }}%)
        {% elif trigger.entity_id == "sensor.master_bathroom_mold_indicator" %}in the Master Bedroom ({{ states.sensor.master_bathroom_mold_indicator.state }}%)
        {% elif trigger.entity_id == "sensor.studio_andrea_mold_indicator" %}in the Studio ({{ states.sensor.studio_andrea_mold_indicator.state }}%)
        {% else %}from Unknown Sensor
        {% endif %}
      data:
        color: "#FF3300"
        sticky: false
        tag: house
        ttl: 0
        clickAction: /lovelace-management/humidity
#  - service: tts.google_say
#    data:
#      entity_id: media_player.studio_andrea_google_mini
#      message: >
#        Mold Alert
#        {% if trigger.entity_id == "sensor.living_room_mold_indicator" %}in the Living Room, it's at {{ states.sensor.living_room_mold_indicator.state }}%
#        {% elif trigger.entity_id == "sensor.kitchen_mold_indicator" %}in the Kitchen Room, it's at {{ states.sensor.kitchen_mold_indicator.state }}%
#        {% elif trigger.entity_id == "sensor.bedroom_luca_mold_indicator" %}in the Luca's Bedroom, it's at {{ states.sensor.bedroom_luca_mold_indicator.state }}%
#        {% elif trigger.entity_id == "sensor.bathroom_mold_indicator" %}in the Bathroom, it's at {{ states.sensor.bathroom_mold_indicator.state }}%
#        {% elif trigger.entity_id == "sensor.master_bedroom_mold_indicator" %}in the Master Bedroom, it's at {{ states.sensor.master_bedroom_mold_indicator.state }}%
#        {% elif trigger.entity_id == "sensor.master_bathroom_mold_indicator" %}in the Master Bedroom, it's at {{ states.sensor.master_bathroom_mold_indicator.state }}%
#        {% elif trigger.entity_id == "sensor.studio_andrea_mold_indicator" %}in the Studio, it's at {{ states.sensor.studio_andrea_mold_indicator.state }}%
#        {% else %}from Unknown Sensor
#        {% endif %}
#      language: 'en'
