---
id: '8298153596081'
alias: House - Night Mode Activated
initial_state: on
trigger:
  - platform: time
    at: "23:00:00"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.night_mode
  - service: input_boolean.turn_off
    entity_id: input_boolean.working_late_andrea
  - service: input_boolean.turn_off
    entity_id: input_boolean.working_late_sonia
