---
id: '2175879175501'
alias: House - Night Mode Deactivated
initial_state: on
trigger:
  - platform: time
    at: "08:00:00"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.night_mode
