---
id: '2175879175501'
alias: House - Night Mode Deactivated
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: "10:00:00"
condition:
  condition: and
  conditions:
    - condition: time
      after: '09:30:00'
      before: '21:00:00'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.night_mode
