---
id: '5054252398489'
alias: House - Volume Set - Night
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.night_mode
    to: 'on'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.studio_google_mini
      volume_level: '0.20'
  - service: media_player.volume_set
    data:
      entity_id: media_player.master_bedroom_echo_dot
      volume_level: '0.05'
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_luca_echo_dot
      volume_level: '0.05'
