---
id: '4029069700947'
alias: House - Volume Set - Day
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.night_mode
    to: 'off'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.studio_andrea_google_mini
      volume_level: '0.45'
  - service: media_player.volume_set
    data:
      entity_id: media_player.master_bedroom_echo_dot
      volume_level: '0.40'
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_luca_echo_dot
      volume_level: '0.40'
