---
id: '0179154356395'
alias: Zigbee - Battery Low
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: numeric_state
    entity_id:
      - sensor.living_room_wsdcgq01lm_battery
      - sensor.kitchen_wsdcgq01lm_battery
      - sensor.studio_andrea_TS0201_battery
      - sensor.studio_andrea_2ajz4kpbs_battery
      - sensor.laundry_room_wxkg03lm_battery
      - sensor.laundry_room_washing_machine_djt11lm_battery
      - sensor.master_bedroom_wxkg02lm_battery
      - sensor.master_bedroom_wsdcgq01lm_battery
      - sensor.master_bathroom_wsdcgq01lm_battery
      - sensor.master_bathroom_sjcgq11lm_battery
      - sensor.bedroom_luca_wsdcgq11lm_battery
      - sensor.bathroom_wsdcgq01lm_battery
      - sensor.bathroom_mccgq01lm_battery
      - sensor.bathroom_mccgq01lm_battery
      - sensor.patio_gzcgq01lm_battery
      - sensor.patio_wsdcgq11lm_battery
      - sensor.patio_mccgq01lm_battery
    below: 20
condition:
  condition: or
  conditions:
    - condition: numeric_state
      entity_id:
        - sensor.living_room_wsdcgq01lm_battery
        - sensor.kitchen_wsdcgq01lm_battery
        - sensor.studio_andrea_TS0201_battery
        - sensor.studio_andrea_2ajz4kpbs_battery
        - sensor.laundry_room_wxkg03lm_battery
        - sensor.laundry_room_washing_machine_djt11lm_battery
        - sensor.master_bedroom_wxkg02lm_battery
        - sensor.master_bedroom_wsdcgq01lm_battery
        - sensor.master_bathroom_wsdcgq01lm_battery
        - sensor.master_bathroom_sjcgq11lm_battery
        - sensor.bedroom_luca_wsdcgq11lm_battery
        - sensor.bathroom_wsdcgq01lm_battery
        - sensor.bathroom_mccgq01lm_battery
        - sensor.bathroom_mccgq01lm_battery
        - sensor.patio_gzcgq01lm_battery
        - sensor.patio_wsdcgq11lm_battery
        - sensor.patio_mccgq01lm_battery
      below: 20
action:
  - service: notify.mobile_app_andrea_oneplus_nord
    data:
      title: "Battery Alert"
      message: "Battery low on Zigbee Device {{ state_attr(trigger.event.data.entity_id, 'friendly_name') }}"
      data:
        color: "#FF66FF"
        sticky: "true"
        tag: tag
        ttl: 0
  - service: notify.telegram_andrea
    data:
      title: "Battery Alert"
      message: "Battery low on Zigbee Device {{ state_attr(trigger.event.data.entity_id, 'friendly_name') }}"
  - service: notify.telegram_andrea
    data:
      title: "Battery Alert"
      message: >-
        {%- set threshold = 20 -%}
        {%- set domains = [states.light, states.switch, states.sensor, states.zwave, states.lock ] -%}
        {%- for domain in domains -%}
        {%- if loop.first -%}
        The following devices have low battery levels:
        {%- endif -%}
        {%- for item in domain if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown")) -%}
        {%- if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) %}
        {{ item.name }} ({{ item.attributes['battery_level'] }}),
        {% endif -%}
        {%- if "battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown") -%}
        {{ item.name }} ({{ item.state }}),
        {% endif -%}
        {%- endfor -%}
        {%- endfor -%}
