---
id: '9339220574211'
alias: Utility Meter - Meter Tariff Change - Llano
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '08:00:00'
  - platform: time
    at: '14:00:00'
  - platform: time
    at: '22:00:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: binary_sensor.workday_es
      state: 'on'
    - condition: not
      conditions:
        - condition: template
          value_template: '{{ now().month == 5 and now().day == 17 }}'
        - condition: template
          value_template: '{{ now().month == 7 and now().day == 25 }}'
    - condition: or
      conditions:
        - condition: time
          after: '08:00:00'
          before: '10:00:00'
        - condition: time
          after: '14:00:00'
          before: '18:00:00'
        - condition: time
          after: '22:00:00'
          before: '00:00:00'
action:
  - service: utility_meter.select_tariff
    data:
      entity_id:
        - utility_meter.house_electricity_daily
        - utility_meter.house_electricity_monthly
        - utility_meter.house_electricity_yearly
      tariff: llano
