---
id: '9339220574213'
alias: Utility Meter - Meter Tariff Change - Valle
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '00:00:00'
condition:
  condition: or
  conditions:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_es
          state: 'off'
        - condition: template
          value_template: '{{ now().month == 5 and now().day == 17 }}'
        - condition: template
          value_template: '{{ now().month == 7 and now().day == 25 }}'
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_es
          state: 'on'
        - condition: not
          conditions:
            - condition: template
              value_template: '{{ now().month == 5 and now().day == 17 }}'
            - condition: template
              value_template: '{{ now().month == 7 and now().day == 25 }}'
        - condition: time
          after: '00:00:00'
          before: '08:00:00'
action:
  - service: select.select_option
    target:
      entity_id: select.house_daily_energy_consumption
    data:
      option: valle
#  - service: utility_meter.select_tariff
#    data:
#      entity_id:
#        - utility_meter.house_electricity_daily
#        - utility_meter.house_electricity_monthly
#        - utility_meter.house_electricity_yearly
#      tariff: valle
