---
id: '8036409997495'
alias: Studio - Sonia - Desk Off
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.studio_sonia_laptop_ping
    to: 'off'
    for:
      seconds: 300
  - platform: state
    entity_id: binary_sensor.studio_sonia_laptop_work_ping
    to: 'off'
    for:
      seconds: 300
  - platform: time
    at: "19:00:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.workday_nl
      state: 'on'
    - condition: state
      entity_id: binary_sensor.studio_sonia_laptop_ping
      state: 'off'
    - condition: state
      entity_id: binary_sensor.studio_sonia_laptop_work_ping
      state: 'off'
    - condition: time
      after: '19:30:00'
      before: '07:30:00'
action:
  - service: switch.turn_off
    entity_id: switch.studio_sonia_plug
