---
id: '5979187123111'
alias: Studio - Sonia - Desk On
initial_state: on
trigger:
#  - platform: state
#    entity_id: binary_sensor.studio_andrea_andrea_desk_sonia_laptop_ping
#    to: 'on'
  - platform: time
    at: "07:00:00"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ is_state('person.sonia', 'home') }}"
    - condition: state
      entity_id: binary_sensor.workday_nl
      state: 'on'
    - condition: time
      after: '07:00:00'
      before: '19:30:00'
action:
  - service: switch.turn_on
    entity_id: switch.studio_andrea_andrea_desk_sonia_plug
