---
id: '5597305899391'
alias: Studio - Desk Sonia Lamp On
initial_state: on
trigger:
  - platform: state
    entity_id: light.studio_sonia_desk_lamp
    from: 'unavailable'
    to: 'on'
action:
  - service: light.turn_on
    entity_id: light.studio_sonia_lamp
  - service: light.turn_off
    entity_id: light.studio_sonia_lamp
