---
id: '1720110542926'
alias: Studio Sonia - Light On
initial_state: on
trigger:
  - platform: state
    entity_id: light.studio_sonia_desk_lamp
    from: 'unavailable'
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.studio_sonia_desk_lamp
          state: "off"
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
action:
  - service: light.turn_off
    data:
      entity_id: light.studio_lights
      transition: 5
